//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Gen Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ___setter_gen. DO NOT EDIT.

package builtins

func (a *Alias) SetU8(val Uint8) *Alias {
	a.U8 = val
	return a
}

func (a *Alias) SetI8(val Int8) *Alias {
	a.I8 = val
	return a
}

func (a *Alias) SetU(val Uint) *Alias {
	a.U = val
	return a
}

func (a *Alias) SetI(val Int) *Alias {
	a.I = val
	return a
}

func (a *Alias) SetStrFunc(val StrFunc) *Alias {
	a.StrFunc = val
	return a
}

func (a *Alias) SetI8Func(val I8Func) *Alias {
	a.I8Func = val
	return a
}

func (a *Alias) SetU8Func(val U8Func) *Alias {
	a.U8Func = val
	return a
}

func (a *Alias) SetInt8(val int8) *Alias {
	a.Int8 = val
	return a
}

func (a *Alias) SetUint8(val uint8) *Alias {
	a.Uint8 = val
	return a
}

func (a *Alias) SetA2(val interface{}) *Alias {
	a.A = val
	return a
}

func (a *Alias) SetB(val byte) *Alias {
	a.b = val
	return a
}

func (a *Alias) SetI2(val int) *Alias {
	a.i = val
	return a
}

func (a *Alias) SetU2(val uint) *Alias {
	a.u = val
	return a
}

func (a *Alias) SetBool(val bool) *Alias {
	a.Bool = val
	return a
}

func (a *Alias) SetByte(val byte) *Alias {
	a.Byte = val
	return a
}

func (a *Alias) SetInt16(val int16) *Alias {
	a.Int16 = val
	return a
}

func (a *Alias) SetInt32(val int32) *Alias {
	a.Int32 = val
	return a
}

func (a *Alias) SetInt64(val int64) *Alias {
	a.Int64 = val
	return a
}

func (a *Alias) SetUint16(val uint16) *Alias {
	a.Uint16 = val
	return a
}

func (a *Alias) SetUint32(val uint32) *Alias {
	a.Uint32 = val
	return a
}

func (a *Alias) SetUint64(val uint64) *Alias {
	a.Uint64 = val
	return a
}

func (a *Alias) SetFloat32(val float32) *Alias {
	a.Float32 = val
	return a
}

func (a *Alias) SetFloat64(val float64) *Alias {
	a.Float64 = val
	return a
}

func (a *Alias) SetString(val string) *Alias {
	a.String = val
	return a
}

func (a *Alias) SetBytes(val []byte) *Alias {
	a.Bytes = val
	return a
}

func (a *Alias) SetBoolP(val *bool) *Alias {
	a.BoolP = val
	return a
}

func (a *Alias) SetByteP(val *byte) *Alias {
	a.ByteP = val
	return a
}

func (a *Alias) SetIntP(val *int) *Alias {
	a.IntP = val
	return a
}

func (a *Alias) SetUintP(val *uint) *Alias {
	a.UintP = val
	return a
}

func (a *Alias) SetBytesP(val *[]byte) *Alias {
	a.BytesP = val
	return a
}

func (a *Alias) SetFloat64P(val *float64) *Alias {
	a.Float64P = val
	return a
}

func (a *Alias) SetStringP(val *string) *Alias {
	a.StringP = val
	return a
}

func (b *Builtins) SetU8(val Uint8) *Builtins {
	b.U8 = val
	return b
}

func (b *Builtins) SetI8(val Int8) *Builtins {
	b.I8 = val
	return b
}

func (b *Builtins) SetU(val Uint) *Builtins {
	b.U = val
	return b
}

func (b *Builtins) SetI(val Int) *Builtins {
	b.I = val
	return b
}

func (b *Builtins) SetStrFunc(val StrFunc) *Builtins {
	b.StrFunc = val
	return b
}

func (b *Builtins) SetI8Func(val I8Func) *Builtins {
	b.I8Func = val
	return b
}

func (b *Builtins) SetU8Func(val U8Func) *Builtins {
	b.U8Func = val
	return b
}

func (b *Builtins) SetInt8(val int8) *Builtins {
	b.Int8 = val
	return b
}

func (b *Builtins) SetUint8(val uint8) *Builtins {
	b.Uint8 = val
	return b
}

func (b *Builtins) SetA(val interface{}) *Builtins {
	b.a = val
	return b
}

func (b *Builtins) SetA2(val interface{}) *Builtins {
	b.A = val
	return b
}

func (b *Builtins) SetB(val byte) *Builtins {
	b.b = val
	return b
}

func (b *Builtins) SetI2(val int) *Builtins {
	b.i = val
	return b
}

func (b *Builtins) SetU2(val uint) *Builtins {
	b.u = val
	return b
}

func (b *Builtins) SetBool(val bool) *Builtins {
	b.Bool = val
	return b
}

func (b *Builtins) SetByte(val byte) *Builtins {
	b.Byte = val
	return b
}

func (b *Builtins) SetInt16(val int16) *Builtins {
	b.Int16 = val
	return b
}

func (b *Builtins) SetInt32(val int32) *Builtins {
	b.Int32 = val
	return b
}

func (b *Builtins) SetInt64(val int64) *Builtins {
	b.Int64 = val
	return b
}

func (b *Builtins) SetUint16(val uint16) *Builtins {
	b.Uint16 = val
	return b
}

func (b *Builtins) SetUint32(val uint32) *Builtins {
	b.Uint32 = val
	return b
}

func (b *Builtins) SetUint64(val uint64) *Builtins {
	b.Uint64 = val
	return b
}

func (b *Builtins) SetFloat32(val float32) *Builtins {
	b.Float32 = val
	return b
}

func (b *Builtins) SetFloat64(val float64) *Builtins {
	b.Float64 = val
	return b
}

func (b *Builtins) SetString(val string) *Builtins {
	b.String = val
	return b
}

func (b *Builtins) SetBytes(val []byte) *Builtins {
	b.Bytes = val
	return b
}

func (b *Builtins) SetBoolP(val *bool) *Builtins {
	b.BoolP = val
	return b
}

func (b *Builtins) SetByteP(val *byte) *Builtins {
	b.ByteP = val
	return b
}

func (b *Builtins) SetIntP(val *int) *Builtins {
	b.IntP = val
	return b
}

func (b *Builtins) SetUintP(val *uint) *Builtins {
	b.UintP = val
	return b
}

func (b *Builtins) SetBytesP(val *[]byte) *Builtins {
	b.BytesP = val
	return b
}

func (b *Builtins) SetFloat64P(val *float64) *Builtins {
	b.Float64P = val
	return b
}

func (b *Builtins) SetStringP(val *string) *Builtins {
	b.StringP = val
	return b
}

func (s *Slice) SetI8S(val []int8) *Slice {
	s.i8S = val
	return s
}

func (s *Slice) SetI8S2(val []*int8) *Slice {
	s.I8S = val
	return s
}

func (s *Slice) SetI8PS(val *[]int8) *Slice {
	s.I8pS = val
	return s
}

func (s *Slice) SetU8S(val []uint8) *Slice {
	s.u8S = val
	return s
}

func (s *Slice) SetU8S2(val []*uint8) *Slice {
	s.U8S = val
	return s
}

func (s *Slice) SetU8PS(val *[]uint8) *Slice {
	s.U8pS = val
	return s
}

func (s *Slice) SetSS(val []string) *Slice {
	s.sS = val
	return s
}

func (s *Slice) SetSS2(val []*string) *Slice {
	s.SS = val
	return s
}

func (s *Slice) SetSpS(val *[]string) *Slice {
	s.SpS = val
	return s
}

func (s *Slice) SetBS(val []byte) *Slice {
	s.bS = val
	return s
}

func (s *Slice) SetBS2(val []*byte) *Slice {
	s.BS = val
	return s
}

func (s *Slice) SetBpS(val *[]byte) *Slice {
	s.BpS = val
	return s
}

func (s *Slice) SetBuiltinsS(val []Builtins) *Slice {
	s.builtinsS = val
	return s
}

func (s *Slice) SetBuiltinsS2(val []*Builtins) *Slice {
	s.BuiltinsS = val
	return s
}

func (s *Slice) SetBuiltinsPs(val *[]Builtins) *Slice {
	s.BuiltinsPs = val
	return s
}
