//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Gen Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ___1option_gen. DO NOT EDIT.

package tags

type NameStructs3 func(*Structs3)

func WithI8NameStructs3(val int8) NameStructs3 {
	return func(object *Structs3) {
		object.i8 = val
	}
}

func WithSNameStructs3(val string) NameStructs3 {
	return func(object *Structs3) {
		object.s = val
	}
}

func WithBNameStructs3(val byte) NameStructs3 {
	return func(object *Structs3) {
		object.b = val
	}
}

func WithU8NameStructs3(val uint) NameStructs3 {
	return func(object *Structs3) {
		object.U8 = val
	}
}

func WithI82NameStructs3(val int8) NameStructs3 {
	return func(object *Structs3) {
		object.I8 = val
	}
}
