//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 Copyright 2022 Galaxyobe.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

// Code generated by ___setter_gen. DO NOT EDIT.

package slice

import (
	builtins "github.com/galaxyobe/gen/cmd/setter-gen/output_tests/builtins"
)

func (a *AliasSlice) SetI8S(val ...*int8) *AliasSlice {
	a.I8S = val
	return a
}

func (a *AliasSlice) SetI8PS(val *[]int8) *AliasSlice {
	a.I8pS = val
	return a
}

func (a *AliasSlice) SetU8S(val ...*uint8) *AliasSlice {
	a.U8S = val
	return a
}

func (a *AliasSlice) SetU8PS(val *[]uint8) *AliasSlice {
	a.U8pS = val
	return a
}

func (a *AliasSlice) SetSS(val ...*string) *AliasSlice {
	a.SS = val
	return a
}

func (a *AliasSlice) SetSpS(val *[]string) *AliasSlice {
	a.SpS = val
	return a
}

func (a *AliasSlice) SetBS(val ...*byte) *AliasSlice {
	a.BS = val
	return a
}

func (a *AliasSlice) SetBpS(val *[]byte) *AliasSlice {
	a.BpS = val
	return a
}

func (a *AliasSlice) SetBuiltinsS(val ...*builtins.Builtins) *AliasSlice {
	a.BuiltinsS = val
	return a
}

func (a *AliasSlice) SetBuiltinsPs(val *[]builtins.Builtins) *AliasSlice {
	a.BuiltinsPs = val
	return a
}

func (s *Slice) SetI8S(val ...int8) *Slice {
	s.i8S = val
	return s
}

func (s *Slice) SetI8S2(val ...*int8) *Slice {
	s.I8S = val
	return s
}

func (s *Slice) SetI8PS(val *[]int8) *Slice {
	s.I8pS = val
	return s
}

func (s *Slice) SetU8S(val ...uint8) *Slice {
	s.u8S = val
	return s
}

func (s *Slice) SetU8S2(val ...*uint8) *Slice {
	s.U8S = val
	return s
}

func (s *Slice) SetU8PS(val *[]uint8) *Slice {
	s.U8pS = val
	return s
}

func (s *Slice) SetSS(val ...string) *Slice {
	s.sS = val
	return s
}

func (s *Slice) SetSS2(val ...*string) *Slice {
	s.SS = val
	return s
}

func (s *Slice) SetSpS(val *[]string) *Slice {
	s.SpS = val
	return s
}

func (s *Slice) SetBS(val ...byte) *Slice {
	s.bS = val
	return s
}

func (s *Slice) SetBS2(val ...*byte) *Slice {
	s.BS = val
	return s
}

func (s *Slice) SetBpS(val *[]byte) *Slice {
	s.BpS = val
	return s
}

func (s *Slice) SetBBS(val ...B) *Slice {
	s.BBS = val
	return s
}

func (s *Slice) SetBuiltinsS(val ...builtins.Builtins) *Slice {
	s.builtinsS = val
	return s
}

func (s *Slice) SetBuiltinsS2(val ...*builtins.Builtins) *Slice {
	s.BuiltinsS = val
	return s
}

func (s *Slice) SetBuiltinsPs(val *[]builtins.Builtins) *Slice {
	s.BuiltinsPs = val
	return s
}
