//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 Copyright 2022 Galaxyobe.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

// Code generated by ___1option_gen. DO NOT EDIT.

package pointer

import (
	builtins "github.com/galaxyobe/gen/cmd/option-gen/output_tests/builtins"
)

type BuiltinsOption func(*Builtins)

func WithU8BuiltinsOption(val builtins.Uint8) BuiltinsOption {
	return func(object *Builtins) {
		object.U8 = val
	}
}

func WithI8BuiltinsOption(val builtins.Int8) BuiltinsOption {
	return func(object *Builtins) {
		object.I8 = val
	}
}

func WithUBuiltinsOption(val builtins.Uint) BuiltinsOption {
	return func(object *Builtins) {
		object.U = val
	}
}

func WithIBuiltinsOption(val builtins.Int) BuiltinsOption {
	return func(object *Builtins) {
		object.I = val
	}
}

func WithStrFuncBuiltinsOption(val builtins.StrFunc) BuiltinsOption {
	return func(object *Builtins) {
		object.StrFunc = val
	}
}

func WithI8FuncBuiltinsOption(val builtins.I8Func) BuiltinsOption {
	return func(object *Builtins) {
		object.I8Func = val
	}
}

func WithU8FuncBuiltinsOption(val builtins.U8Func) BuiltinsOption {
	return func(object *Builtins) {
		object.U8Func = val
	}
}

func WithInt8BuiltinsOption(val int8) BuiltinsOption {
	return func(object *Builtins) {
		object.Int8 = val
	}
}

func WithUint8BuiltinsOption(val uint8) BuiltinsOption {
	return func(object *Builtins) {
		object.Uint8 = val
	}
}

func WithABuiltinsOption(val interface{}) BuiltinsOption {
	return func(object *Builtins) {
		object.A = val
	}
}

func WithBoolBuiltinsOption(val bool) BuiltinsOption {
	return func(object *Builtins) {
		object.Bool = val
	}
}

func WithByteBuiltinsOption(val byte) BuiltinsOption {
	return func(object *Builtins) {
		object.Byte = val
	}
}

func WithInt16BuiltinsOption(val int16) BuiltinsOption {
	return func(object *Builtins) {
		object.Int16 = val
	}
}

func WithInt32BuiltinsOption(val int32) BuiltinsOption {
	return func(object *Builtins) {
		object.Int32 = val
	}
}

func WithInt64BuiltinsOption(val int64) BuiltinsOption {
	return func(object *Builtins) {
		object.Int64 = val
	}
}

func WithUint16BuiltinsOption(val uint16) BuiltinsOption {
	return func(object *Builtins) {
		object.Uint16 = val
	}
}

func WithUint32BuiltinsOption(val uint32) BuiltinsOption {
	return func(object *Builtins) {
		object.Uint32 = val
	}
}

func WithUint64BuiltinsOption(val uint64) BuiltinsOption {
	return func(object *Builtins) {
		object.Uint64 = val
	}
}

func WithFloat32BuiltinsOption(val float32) BuiltinsOption {
	return func(object *Builtins) {
		object.Float32 = val
	}
}

func WithFloat64BuiltinsOption(val float64) BuiltinsOption {
	return func(object *Builtins) {
		object.Float64 = val
	}
}

func WithStringBuiltinsOption(val string) BuiltinsOption {
	return func(object *Builtins) {
		object.String = val
	}
}

func WithBytesBuiltinsOption(val ...byte) BuiltinsOption {
	return func(object *Builtins) {
		object.Bytes = val
	}
}

func WithBoolPBuiltinsOption(val *bool) BuiltinsOption {
	return func(object *Builtins) {
		object.BoolP = val
	}
}

func WithBytePBuiltinsOption(val *byte) BuiltinsOption {
	return func(object *Builtins) {
		object.ByteP = val
	}
}

func WithIntPBuiltinsOption(val *int) BuiltinsOption {
	return func(object *Builtins) {
		object.IntP = val
	}
}

func WithUintPBuiltinsOption(val *uint) BuiltinsOption {
	return func(object *Builtins) {
		object.UintP = val
	}
}

func WithBytesPBuiltinsOption(val *[]byte) BuiltinsOption {
	return func(object *Builtins) {
		object.BytesP = val
	}
}

func WithFloat64PBuiltinsOption(val *float64) BuiltinsOption {
	return func(object *Builtins) {
		object.Float64P = val
	}
}

func WithStringPBuiltinsOption(val *string) BuiltinsOption {
	return func(object *Builtins) {
		object.StringP = val
	}
}
