//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Gen Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ___setter_gen. DO NOT EDIT.

package structs

import (
	builtins "github.com/galaxyobe/gen/cmd/setter-gen/output_tests/builtins"
)

func (a *Alias) SetU8(val builtins.Uint8) *Alias {
	a.U8 = val
	return a
}

func (a *Alias) SetI8(val builtins.Int8) *Alias {
	a.I8 = val
	return a
}

func (a *Alias) SetU(val builtins.Uint) *Alias {
	a.U = val
	return a
}

func (a *Alias) SetI(val builtins.Int) *Alias {
	a.I = val
	return a
}

func (a *Alias) SetStrFunc(val builtins.StrFunc) *Alias {
	a.StrFunc = val
	return a
}

func (a *Alias) SetI8Func(val builtins.I8Func) *Alias {
	a.I8Func = val
	return a
}

func (a *Alias) SetU8Func(val builtins.U8Func) *Alias {
	a.U8Func = val
	return a
}

func (a *Alias) SetInt8(val int8) *Alias {
	a.Int8 = val
	return a
}

func (a *Alias) SetUint8(val uint8) *Alias {
	a.Uint8 = val
	return a
}

func (a *Alias) SetBool(val bool) *Alias {
	a.Bool = val
	return a
}

func (a *Alias) SetByte(val byte) *Alias {
	a.Byte = val
	return a
}

func (a *Alias) SetInt16(val int16) *Alias {
	a.Int16 = val
	return a
}

func (a *Alias) SetInt32(val int32) *Alias {
	a.Int32 = val
	return a
}

func (a *Alias) SetInt64(val int64) *Alias {
	a.Int64 = val
	return a
}

func (a *Alias) SetUint16(val uint16) *Alias {
	a.Uint16 = val
	return a
}

func (a *Alias) SetUint32(val uint32) *Alias {
	a.Uint32 = val
	return a
}

func (a *Alias) SetUint64(val uint64) *Alias {
	a.Uint64 = val
	return a
}

func (a *Alias) SetFloat32(val float32) *Alias {
	a.Float32 = val
	return a
}

func (a *Alias) SetFloat64(val float64) *Alias {
	a.Float64 = val
	return a
}

func (a *Alias) SetString(val string) *Alias {
	a.String = val
	return a
}

func (a *Alias) SetBytes(val []byte) *Alias {
	a.Bytes = val
	return a
}

func (a *Alias) SetBoolP(val *bool) *Alias {
	a.BoolP = val
	return a
}

func (a *Alias) SetByteP(val *byte) *Alias {
	a.ByteP = val
	return a
}

func (a *Alias) SetIntP(val *int) *Alias {
	a.IntP = val
	return a
}

func (a *Alias) SetUintP(val *uint) *Alias {
	a.UintP = val
	return a
}

func (a *Alias) SetBytesP(val *[]byte) *Alias {
	a.BytesP = val
	return a
}

func (a *Alias) SetFloat64P(val *float64) *Alias {
	a.Float64P = val
	return a
}

func (a *Alias) SetStringP(val *string) *Alias {
	a.StringP = val
	return a
}

func (s *Structs) Setb(val byte) *Structs {
	s.b = val
	return s
}

func (s *Structs) Setu(val uint8) *Structs {
	s.u = val
	return s
}

func (s *Structs) Seti(val int8) *Structs {
	s.i = val
	return s
}

func (s *Structs) SetString(val string) *Structs {
	s.String = val
	return s
}

func (s *Structs) SetBuiltins(val builtins.Builtins) *Structs {
	s.Builtins = val
	return s
}

func (s *Structs) SetBuiltins1(val builtins.Builtins) *Structs {
	s.Builtins1 = val
	return s
}

func (s *Structs) SetBuiltins2(val *builtins.Builtins) *Structs {
	s.Builtins2 = val
	return s
}

func (s *Structs) SetUser(val User) *Structs {
	s.User = val
	return s
}

func (s *Structs) SetUser2(val User) *Structs {
	s.User2 = val
	return s
}

func (s *Structs) SetUser3(val *User) *Structs {
	s.User3 = val
	return s
}

func (s *Structs) SetAge(val Age) *Structs {
	s.Age = val
	return s
}

func (u *User) SetName(val string) *User {
	u.Name = val
	return u
}

func (u *User) SetAge(val Age) *User {
	u.Age = val
	return u
}

func (u *UserInfo) SetName(val string) *UserInfo {
	u.Name = val
	return u
}

func (u *UserInfo) SetAge(val Age) *UserInfo {
	u.Age = val
	return u
}
